inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

Style/ClassAndModuleChildren:
  Enabled:
    false
