inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/CaseEquality:
  Exclude:
    - lib/bcdd/result/expectations/contract/for_types_and_values.rb

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/SingleLineMethods:
  Enabled: false

Style/MapToSet:
  Exclude:
    - lib/bcdd/result/expectations/contract/for_types.rb

Style/MixinGrouping:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - bcdd-result.gemspec
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Minitest/MultipleAssertions:
  Enabled: false

Minitest/AssertEmptyLiteral:
  Enabled: false
