inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Lint/RescueException:
  Exclude:
    - lib/bcdd/result/transitions/tracking/enabled.rb

Layout/LineLength:
  Max: 120

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - lib/bcdd/result/transitions/listener.rb

Style/AccessModifierDeclarations:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/ParallelAssignment:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/MapToSet:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - bcdd-result.gemspec
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - lib/bcdd/result.rb
    - test/**/*.rb

Minitest/MultipleAssertions:
  Enabled: false

Minitest/AssertEmptyLiteral:
  Enabled: false

Minitest/AssertOperator:
  Enabled: false

Minitest/AssertWithExpectedArgument:
  Exclude:
    - test/test_helper.rb

Naming/FileName:
  Exclude:
    - lib/bcdd-result.rb
