inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/MapToSet:
  Exclude:
    - lib/bcdd/result/expectations/contract/for_types.rb

Style/CaseEquality:
  Exclude:
    - lib/bcdd/result/expectations/contract/for_types_and_values.rb

Naming/MethodName:
  Exclude:
    - lib/bcdd/result/mixin.rb

Minitest/MultipleAssertions:
  Enabled: false
